version: '3.9'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://adorabat:adorabat@db:5432/mydb
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: adorabat
      POSTGRES_PASSWORD: adorabat
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
